name: Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --prefer-offline

      - name: Run linter for scripts
        run: yarn xo

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --prefer-offline

      - name: Run tests
        run: yarn test --ci --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_DIR: ./reports/tests/

      - name: Upload jest junit test results
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: jest-test-results
          path: reports/tests/junit.xml

      - name: Upload code coverage to codecov
        uses: codecov/codecov-action@v2
